### PR TITLE
Some fixes and new features

### PR DESCRIPTION
**Pull request by klaus3000**
Hi Duane!

I made some fixes and new features for dnscap. If you want to merge them, I could delete my dnscap fork (there are already enough dnscap forks on github)

### CODE REVIEW

**Comment by ikoniaris** [comment]
Hi @klaus3000 and @kiall, how about you submit the debian packaging as a separate PR? Otherwise do you mind if I do?

**Comment by klaus3000** [comment]
No, I don't mind.
@wessels How shall we proceed?

**Comment by wessels** [comment]
Okay I guess the best thing to do is close this and have you send smaller pull requests including the debian packaging?

**Comment by lafeuil** [comment]
If you want debian packaging for dnscap, I have created a patch in my [repository](https://github.com/lafeuil/dnscap). If you want, I submit a pull request.

**Comment by wessels** [comment]
Yes please submit a request rather than rely on me to get it right!

**Pull request closed without merging**
